[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "optimal_morphology_rl"
version = "0.1.0"
authors = [{ name = "Valentin Yuryev", email = "valentin.yuryev@gmail.com" }]
maintainers = [
    { name = "Valentin Yuryev", email = "valentin.yuryev@gmail.com" },
]
description = "RL to find optimal morphology"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "torch",
    "pyyaml",
    "omegaconf",
    "numpy",
    "time_series_buffer",
    "vlearn_train",
    "optimal_morphology_rl_assets",
]

[project.optional-dependencies]
test = ["pytest>=8.0"]

[tool.uv.sources]
vlearn_train = { workspace = true, editable = true }
optimal_morphology_rl_assets = { workspace = true, editable = true }
time_series_buffer = { git = "https://github.com/goodfaiter/time_series_buffer.git", branch = "main" }

[tool.hatch.build.targets.wheel]
packages = ["src/optimal_morphology_rl"]

[tool.ruff]
line-length = 140

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
