# Adapted from https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/cfg/train/HumanoidPPO.yaml
params:
  seed: 200964

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: default
          val: 0
        fixed_sigma: True

    mlp:
      units: [64, 32, 16]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

          #load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
          #load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: Finger_EE_Tracking
    env_name: finger_ee_tracking-env
      #train_dir: ${log_dir}
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: 4096
    reward_shaper:
      scale_value: 0.1
    normalize_advantage: True
    gamma: 0.95
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: fixed
    # lr_schedule: linear
    # kl_threshold: 0.008
    kl_threshold: 0.016
    score_to_win: 20000000
    max_epochs: 500 
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.00004
    truncate_grads: True
    ppo: True
    e_clip: 0.2
    horizon_length: 64
    minibatch_size: 131072
    mini_epochs: 4
    critic_coef: 4
    clip_actions: False
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0001
      # player:
      #   deterministic: True
      #   use_vecenv: True
      #   games_num: 1000000
      #   print_stats: False 