params:
  seed: 200964

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: transformer_actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: default
          val: 0
        fixed_sigma: True

    transformer:
      seq_len:    30  # must match hist_size in the env
      hidden_dim: 64
      num_heads:  4  # hidden_dim % num_heads == 0
      num_layers: 2
      dropout:    0.0

  config:
    name: finger_ee_tracking
    env_name: finger_ee_tracking_env
      #train_dir: ${log_dir}
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: False
    value_bootstrap: True
    num_actors: 4096
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.95
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: fixed
    # lr_schedule: linear
    # kl_threshold: 0.008
    kl_threshold: 0.016
    score_to_win: 20000000
    max_epochs: 1000
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    ppo: True
    e_clip: 0.2
    horizon_length: 128
    minibatch_size: 1024
    mini_epochs: 1
    critic_coef: 1.0
    clip_actions: False
    clip_value: False
    seq_length: 1
    bounds_loss_coef: 0.0
      # player:
      #   deterministic: True
      #   use_vecenv: True
      #   games_num: 1000000
      #   print_stats: False 