params:
  seed: 200964

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    mlp:
      units: [512, 256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  config:
    name: hand_object
    env_name: hand_object_env
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: 4096
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.96
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: fixed
    kl_threshold: 0.016
    score_to_win: 20000000
    max_epochs: 5000
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    ppo: True
    e_clip: 0.2
    horizon_length: 128
    minibatch_size: 4096
    mini_epochs: 1
    critic_coef: 1.0
    clip_actions: False
    clip_value: False
    seq_length: 4
    bounds_loss_coef: 0.0
